// <auto-generated />
using System;
using AspNetCoreApiStarter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspNetCoreApiStarter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreApiStarter.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("AspNetCoreApiStarter.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AspNetCoreApiStarter.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("AspNetCoreApiStarter.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("ReplacedByTokenHash").HasColumnType("text");
                    b.Property<DateTime?>("RevokedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("TokenHash").IsRequired().HasColumnType("text");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("TokenHash").IsUnique();
                    b.HasIndex("UserId");
                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AspNetCoreApiStarter.Models.RevokedAccessToken", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("RevokedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("JwtId").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("JwtId").IsUnique();
                    b.ToTable("RevokedAccessTokens");
                });

            modelBuilder.Entity("AspNetCoreApiStarter.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Phone")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AspNetCoreApiStarter.Models.EmailActionToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("DeletedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<bool>("IsDeleted").HasColumnType("boolean");
                    b.Property<string>("Purpose").IsRequired().HasColumnType("text");
                    b.Property<string>("TokenHash").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("UsedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("TokenHash").IsUnique();
                    b.HasIndex("UserId", "Purpose", "UsedAt");
                    b.HasIndex("UserId");
                    b.ToTable("EmailActionTokens");
                });

            modelBuilder.Entity("AspNetCoreApiStarter.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<int>("Attempts").HasColumnType("integer");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("DeletedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("EventType").IsRequired().HasColumnType("text");
                    b.Property<bool>("IsDeleted").HasColumnType("boolean");
                    b.Property<string>("LastError").HasColumnType("text");
                    b.Property<string>("Payload").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("OccurredAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("ProcessedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("ProcessedAt", "OccurredAt");
                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("AspNetCoreApiStarter.Models.RolePermission", b =>
                {
                    b.HasOne("AspNetCoreApiStarter.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApiStarter.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AspNetCoreApiStarter.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AspNetCoreApiStarter.Models.RefreshToken", b =>
                {
                    b.HasOne("AspNetCoreApiStarter.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("AspNetCoreApiStarter.Models.EmailActionToken", b =>
                {
                    b.HasOne("AspNetCoreApiStarter.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
